language: objective-c
before_script:
  - brew update
  - brew install ant
  - brew tap homebrew/homebrew-php
  - brew install php56
# flash player debugger
  - brew install caskroom/cask/brew-cask
  - brew cask install flash-player-debugger
# apache flex sdk
  - wget -O flex_sdk.zip http://www.apache.org/dist/flex/4.14.0/binaries/apache-flex-sdk-4.14.0-bin.zip
  - unzip -q flex_sdk.zip -d flex_sdk
  - wget -O playerglobal.swc http://download.macromedia.com/get/flashplayer/updaters/14/playerglobal14_0.swc
  - mkdir -p flex_sdk/frameworks/libs/player/11.1
  - cp playerglobal.swc flex_sdk/frameworks/libs/player/11.1
  - echo env.PLAYERGLOBAL_HOME=libs/player > flex_sdk/env.properties
# apache flex unit
  - wget -O flexunit.zip http://mirrors.gigenet.com/apache/flex/flexunit/4.2.0/binaries/apache-flex-flexunit-4.2.0-4.12.0-bin.zip
  - unzip -q flexunit.zip
  - mkdir -p tests/libs
  - cp flexunit/flexunit-*-as3_*.swc tests/libs
  - cp flexunit/flexunit-cilistener-*.swc tests/libs
  - cp flexunit/flexunit-uilistener-*.swc tests/libs
# php
  - php -d always_populate_raw_post_data="-1" -S 127.0.0.1:4000 &
script:
  - ant -DFLEX_HOME "flex_sdk" -DFLEXUNIT "flexunit" -DFLASHPLAYER "$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"
  - test -f tests/fixtures/FlexButtonTest.labelAndSize-actual.png